# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:  
  adapter: postgresql
  encoding: unicode
  database: mysite
  pool: 5
  username: 
  password: theduke23

test:  
  adapter: postgresql
  encoding: unicode
  database: mysite
  pool: 5
  username: 
  password: theduke23


# production:
#   <<: *default
#   database: my_production_database
#   username: tonycarballeira
#   password: theduke23
